// Code generated by go-swagger; DO NOT EDIT.

package timesheet_job_rest_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "pfistera/swagger_client/models"
)

// RetrieveAllTimeSheetJobsUsingGETReader is a Reader for the RetrieveAllTimeSheetJobsUsingGET structure.
type RetrieveAllTimeSheetJobsUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RetrieveAllTimeSheetJobsUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRetrieveAllTimeSheetJobsUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewRetrieveAllTimeSheetJobsUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewRetrieveAllTimeSheetJobsUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewRetrieveAllTimeSheetJobsUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRetrieveAllTimeSheetJobsUsingGETOK creates a RetrieveAllTimeSheetJobsUsingGETOK with default headers values
func NewRetrieveAllTimeSheetJobsUsingGETOK() *RetrieveAllTimeSheetJobsUsingGETOK {
	return &RetrieveAllTimeSheetJobsUsingGETOK{}
}

/*RetrieveAllTimeSheetJobsUsingGETOK handles this case with default header values.

OK
*/
type RetrieveAllTimeSheetJobsUsingGETOK struct {
	Payload []*models.TimesheetJob
}

func (o *RetrieveAllTimeSheetJobsUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /api/timesheetjob][%d] retrieveAllTimeSheetJobsUsingGETOK  %+v", 200, o.Payload)
}

func (o *RetrieveAllTimeSheetJobsUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRetrieveAllTimeSheetJobsUsingGETUnauthorized creates a RetrieveAllTimeSheetJobsUsingGETUnauthorized with default headers values
func NewRetrieveAllTimeSheetJobsUsingGETUnauthorized() *RetrieveAllTimeSheetJobsUsingGETUnauthorized {
	return &RetrieveAllTimeSheetJobsUsingGETUnauthorized{}
}

/*RetrieveAllTimeSheetJobsUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type RetrieveAllTimeSheetJobsUsingGETUnauthorized struct {
}

func (o *RetrieveAllTimeSheetJobsUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/timesheetjob][%d] retrieveAllTimeSheetJobsUsingGETUnauthorized ", 401)
}

func (o *RetrieveAllTimeSheetJobsUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRetrieveAllTimeSheetJobsUsingGETForbidden creates a RetrieveAllTimeSheetJobsUsingGETForbidden with default headers values
func NewRetrieveAllTimeSheetJobsUsingGETForbidden() *RetrieveAllTimeSheetJobsUsingGETForbidden {
	return &RetrieveAllTimeSheetJobsUsingGETForbidden{}
}

/*RetrieveAllTimeSheetJobsUsingGETForbidden handles this case with default header values.

Forbidden
*/
type RetrieveAllTimeSheetJobsUsingGETForbidden struct {
}

func (o *RetrieveAllTimeSheetJobsUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /api/timesheetjob][%d] retrieveAllTimeSheetJobsUsingGETForbidden ", 403)
}

func (o *RetrieveAllTimeSheetJobsUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRetrieveAllTimeSheetJobsUsingGETNotFound creates a RetrieveAllTimeSheetJobsUsingGETNotFound with default headers values
func NewRetrieveAllTimeSheetJobsUsingGETNotFound() *RetrieveAllTimeSheetJobsUsingGETNotFound {
	return &RetrieveAllTimeSheetJobsUsingGETNotFound{}
}

/*RetrieveAllTimeSheetJobsUsingGETNotFound handles this case with default header values.

Not Found
*/
type RetrieveAllTimeSheetJobsUsingGETNotFound struct {
}

func (o *RetrieveAllTimeSheetJobsUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /api/timesheetjob][%d] retrieveAllTimeSheetJobsUsingGETNotFound ", 404)
}

func (o *RetrieveAllTimeSheetJobsUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
