// Code generated by go-swagger; DO NOT EDIT.

package basic_error_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewErrorHTMLUsingPOSTParams creates a new ErrorHTMLUsingPOSTParams object
// with the default values initialized.
func NewErrorHTMLUsingPOSTParams() *ErrorHTMLUsingPOSTParams {

	return &ErrorHTMLUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewErrorHTMLUsingPOSTParamsWithTimeout creates a new ErrorHTMLUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewErrorHTMLUsingPOSTParamsWithTimeout(timeout time.Duration) *ErrorHTMLUsingPOSTParams {

	return &ErrorHTMLUsingPOSTParams{

		timeout: timeout,
	}
}

// NewErrorHTMLUsingPOSTParamsWithContext creates a new ErrorHTMLUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewErrorHTMLUsingPOSTParamsWithContext(ctx context.Context) *ErrorHTMLUsingPOSTParams {

	return &ErrorHTMLUsingPOSTParams{

		Context: ctx,
	}
}

// NewErrorHTMLUsingPOSTParamsWithHTTPClient creates a new ErrorHTMLUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewErrorHTMLUsingPOSTParamsWithHTTPClient(client *http.Client) *ErrorHTMLUsingPOSTParams {

	return &ErrorHTMLUsingPOSTParams{
		HTTPClient: client,
	}
}

/*ErrorHTMLUsingPOSTParams contains all the parameters to send to the API endpoint
for the error Html using p o s t operation typically these are written to a http.Request
*/
type ErrorHTMLUsingPOSTParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the error Html using p o s t params
func (o *ErrorHTMLUsingPOSTParams) WithTimeout(timeout time.Duration) *ErrorHTMLUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the error Html using p o s t params
func (o *ErrorHTMLUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the error Html using p o s t params
func (o *ErrorHTMLUsingPOSTParams) WithContext(ctx context.Context) *ErrorHTMLUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the error Html using p o s t params
func (o *ErrorHTMLUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the error Html using p o s t params
func (o *ErrorHTMLUsingPOSTParams) WithHTTPClient(client *http.Client) *ErrorHTMLUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the error Html using p o s t params
func (o *ErrorHTMLUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ErrorHTMLUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
