// Code generated by go-swagger; DO NOT EDIT.

package timesheet_job_rest_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRetrieveAllTimeSheetJobsUsingGETParams creates a new RetrieveAllTimeSheetJobsUsingGETParams object
// with the default values initialized.
func NewRetrieveAllTimeSheetJobsUsingGETParams() *RetrieveAllTimeSheetJobsUsingGETParams {

	return &RetrieveAllTimeSheetJobsUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRetrieveAllTimeSheetJobsUsingGETParamsWithTimeout creates a new RetrieveAllTimeSheetJobsUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRetrieveAllTimeSheetJobsUsingGETParamsWithTimeout(timeout time.Duration) *RetrieveAllTimeSheetJobsUsingGETParams {

	return &RetrieveAllTimeSheetJobsUsingGETParams{

		timeout: timeout,
	}
}

// NewRetrieveAllTimeSheetJobsUsingGETParamsWithContext creates a new RetrieveAllTimeSheetJobsUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewRetrieveAllTimeSheetJobsUsingGETParamsWithContext(ctx context.Context) *RetrieveAllTimeSheetJobsUsingGETParams {

	return &RetrieveAllTimeSheetJobsUsingGETParams{

		Context: ctx,
	}
}

// NewRetrieveAllTimeSheetJobsUsingGETParamsWithHTTPClient creates a new RetrieveAllTimeSheetJobsUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRetrieveAllTimeSheetJobsUsingGETParamsWithHTTPClient(client *http.Client) *RetrieveAllTimeSheetJobsUsingGETParams {

	return &RetrieveAllTimeSheetJobsUsingGETParams{
		HTTPClient: client,
	}
}

/*RetrieveAllTimeSheetJobsUsingGETParams contains all the parameters to send to the API endpoint
for the retrieve all time sheet jobs using g e t operation typically these are written to a http.Request
*/
type RetrieveAllTimeSheetJobsUsingGETParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the retrieve all time sheet jobs using g e t params
func (o *RetrieveAllTimeSheetJobsUsingGETParams) WithTimeout(timeout time.Duration) *RetrieveAllTimeSheetJobsUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the retrieve all time sheet jobs using g e t params
func (o *RetrieveAllTimeSheetJobsUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the retrieve all time sheet jobs using g e t params
func (o *RetrieveAllTimeSheetJobsUsingGETParams) WithContext(ctx context.Context) *RetrieveAllTimeSheetJobsUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the retrieve all time sheet jobs using g e t params
func (o *RetrieveAllTimeSheetJobsUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the retrieve all time sheet jobs using g e t params
func (o *RetrieveAllTimeSheetJobsUsingGETParams) WithHTTPClient(client *http.Client) *RetrieveAllTimeSheetJobsUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the retrieve all time sheet jobs using g e t params
func (o *RetrieveAllTimeSheetJobsUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *RetrieveAllTimeSheetJobsUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
