// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"pfistera/swagger_client/client/basic_error_controller"
	"pfistera/swagger_client/client/job_rest_controller"
	"pfistera/swagger_client/client/timesheet_job_rest_controller"
	"pfistera/swagger_client/client/timesheet_rest_controller"
	"pfistera/swagger_client/client/web_mvc_links_handler"
)

// Default API documentation HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost:8081"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/ts"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new API documentation HTTP client.
func NewHTTPClient(formats strfmt.Registry) *APIDocumentation {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new API documentation HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *APIDocumentation {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new API documentation client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *APIDocumentation {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(APIDocumentation)
	cli.Transport = transport

	cli.BasicErrorController = basic_error_controller.New(transport, formats)

	cli.JobRestController = job_rest_controller.New(transport, formats)

	cli.TimesheetJobRestController = timesheet_job_rest_controller.New(transport, formats)

	cli.TimesheetRestController = timesheet_rest_controller.New(transport, formats)

	cli.WebMvcLinksHandler = web_mvc_links_handler.New(transport, formats)

	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// APIDocumentation is a client for API documentation
type APIDocumentation struct {
	BasicErrorController *basic_error_controller.Client

	JobRestController *job_rest_controller.Client

	TimesheetJobRestController *timesheet_job_rest_controller.Client

	TimesheetRestController *timesheet_rest_controller.Client

	WebMvcLinksHandler *web_mvc_links_handler.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *APIDocumentation) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.BasicErrorController.SetTransport(transport)

	c.JobRestController.SetTransport(transport)

	c.TimesheetJobRestController.SetTransport(transport)

	c.TimesheetRestController.SetTransport(transport)

	c.WebMvcLinksHandler.SetTransport(transport)

}
