// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TimesheetJob TimesheetJob
// swagger:model TimesheetJob
type TimesheetJob struct {

	// job
	Job *Job `json:"job,omitempty"`

	// remark
	Remark string `json:"remark,omitempty"`

	// timesheet
	Timesheet *Timesheet `json:"timesheet,omitempty"`

	// tsjob id
	TsjobID int64 `json:"tsjob_id,omitempty"`
}

// Validate validates this timesheet job
func (m *TimesheetJob) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJob(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTimesheet(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TimesheetJob) validateJob(formats strfmt.Registry) error {

	if swag.IsZero(m.Job) { // not required
		return nil
	}

	if m.Job != nil {
		if err := m.Job.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("job")
			}
			return err
		}
	}

	return nil
}

func (m *TimesheetJob) validateTimesheet(formats strfmt.Registry) error {

	if swag.IsZero(m.Timesheet) { // not required
		return nil
	}

	if m.Timesheet != nil {
		if err := m.Timesheet.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("timesheet")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TimesheetJob) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TimesheetJob) UnmarshalBinary(b []byte) error {
	var res TimesheetJob
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
