apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: load-balancer-apf-minikube
  name: apf-minikube
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: load-balancer-apf-minikube
  template:
    metadata:
      labels:
        app.kubernetes.io/name: load-balancer-apf-minikube
    spec:
      containers:
        - image: apf-minikube:latest
          name: apf-minikube
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: KLAUS_PORT
              value: "8080"
